---
- hosts: localhost
  become: yes
  become_user: root
  roles:
    - role: nginxinc.nginx
  vars:
    nginx_start: false
    nginx_http_template_enable: true
    nginx_http_template:
      default:
        template_file: http/default.conf.j2
        conf_file_name: default.conf
        conf_file_location: /etc/nginx/conf.d/
        servers:
          server1:
            listen:
              listen_localhost:
                port: 80
                ssl: false
            server_name: localhost
            web_server:
              locations:
                default:
                  location: /
                  html_file_location: /html
                  html_file_name: index.html
                  autoindex: false
              http_demo_conf: false
  tasks:
  - name: Created /html directory
    file:
      path: /html
      owner: root
      group: root
      mode: '0644'
      state: directory
